
USE EXERCISES
CREATE TABLE Passports
(
PassportID INT PRIMARY KEY,
PassportNumber NVARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Persons
(
PersonID INT PRIMARY KEY IDENTITY NOT NULL,
FirstName NVARCHAR(50) NOT NULL,
Salary DECIMAL(18,2),
PassportID INT FOREIGN KEY REFERENCES Passports(PassportID)
)

CREATE TABLE Manufacturers
(
ManufacturerID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] NVARCHAR(20) NOT NULL,
EstablishedOn DATE
)

CREATE TABLE Models
(
ModelID INT PRIMARY KEY IDENTITY(100,1),
[Name] NVARCHAR(20) NOT NULL,
ManufacturerID INT FOREIGN KEY REFERENCES Manufacturers(ManufacturerID)
)

CREATE TABLE Students
(
StudentID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] NVARCHAR(30) NOT NULL,
)

CREATE TABLE Exams
(
ExamID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] NVARCHAR(30) NOT NULL
)

CREATE TABLE StudentsExams 
(
StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
ExamID INT FOREIGN KEY REFERENCES Exams (ExamID)
CONSTRAINT PK_StudentExam PRIMARY KEY(StudentID,ExamID)
)

CREATE TABLE Teachers
(
TeacherID INT PRIMARY KEY NOT NULL,
[Name] NVARCHAR(30) NOT NULL,
ManagerID INT FOREIGN KEY REFERENCES Teachers (TeacherID)
)

CREATE TABLE Cities
(
CityID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Customers
(
CustomerID  INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50) NOT NULL,
Birthday DATE,
CityID INT FOREIGN KEY REFERENCES Cities(CityID) NOT NULL
)

CREATE TABLE ItemTypes
(
ItemTypeID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Items
(
ItemID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(50) NOT NULL,
ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE Orders
(
OrderID INT PRIMARY KEY IDENTITY NOT NULL,
CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID)
)

CREATE TABLE OrderItems
(
OrderID INT FOREIGN KEY REFERENCES Orders(OrderID) NOT NULL,
ItemID INT FOREIGN KEY REFERENCES Items(ItemID)NOT NULL,
CONSTRAINT PK_OrderItems PRIMARY KEY(OrderId,ItemID)
)

CREATE TABLE Subjects
(
SubjectID INT PRIMARY KEY IDENTITY NOT NULL,
SubjectName VARCHAR(50) NOT NULL
)

CREATE TABLE Majors
(
MajorID INT PRIMARY KEY IDENTITY NOT NULL,
[Name] varchar(30) NOT NULL
)

CREATE TABLE Students
(
StudentID  INT PRIMARY KEY IDENTITY NOT NULL,
StudentNumber varchar(20) NOT NULL,
StudentName varchar(50) NOT NULL,
MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Agenda
(
StudentID INT FOREIGN KEY REFERENCES Students(StudentID)  NOT NULL,
SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID) NOT NULL,
CONSTRAINT PK_StudentSubject PRIMARY KEY(StudentID,SubjectID)
)

CREATE TABLE Payments
(
PaymentID INT PRIMARY KEY IDENTITY NOT NULL,
PaymentDate DATETIME2 NOT NULL,
PaymentAmount DECIMAL(10,2) NOT NULL,
StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
)

USE Geography
SELECT M.MountainRange ='Rila'
FROM Mountains AS M